# publish on ig

name: Release new package

on:
  workflow_call:
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: insightsengineering/disk-space-reclaimer@v1
        with:
          tools-cache: false
          android: true
          
      - name: size        
        run: |
          df -h


      - name: Get IG-website-release
        uses: actions/checkout@main
        with:
          persist-credentials: false
          repository: ansforge/IG-website-release
          path: IG-website-release
  
      - name: Init        
        run: |
          cd  IG-website-release
          git submodule update --init --recursive
          
      - uses: actions/checkout@v3
        with:      
          path: igRepo


      - name: Get From site esante     
        run: |
          #Creation des répertoires d'init
          #mkdir  ./igRepo/input/images/NOS/
          mkdir ./igRepo/input/NOS
          #Recuperation des NOS en json
          wget -q https://esante.gouv.fr/sites/default/files/media_entity/documents/NOS-Fichiers_Publics-Versions_json_fhir.zip
          unzip NOS-Fichiers_Publics-Versions_json_fhir.zip -d ./igRepo/input/NOS

          #Suppression des fichiers en erreur
          rm  -f ./igRepo/input/NOS/TRE_R13-CommuneOM-FHIR.json
          rm  -f ./igRepo/input/NOS/ASS_X12-CommuneDeptRegionOM-FHIR.json
          rm   -f ./igRepo/input/NOS/JDV_J120-CommuneHistorisee-FHIR.json
          rm   -f  ./igRepo/input/NOS/JDV_J124-Commune-FHIR.json
          #rm ./input/NOS/ASS_A11-CorresModeleCDA-XdsFormatCode-CISIS-FHIR.json
          #rm ./input/NOS/ASS_X16-CorrespondanceType-Classe-DMP-FHIR.json
          rm  -f ./igRepo/input/NOS/JDV_J151-BodySiteBodyTemperature-ENS-FHIR.json
          rm  -f ./igRepo/input/NOS/ASS_* 


          

      - name: Install Sushi
        run: npm install -g fsh-sushi

      - name: Install ruby and jekyll      
        run: |
          sudo apt-get install ruby-full
          sudo gem install jekyll

                

      # Downloads the newest version of the IG Publisher, this could probable be cached.
      - name: 📥 Download IG Publisher
        run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/download/1.6.11/publisher.jar
          

      - name: Run sushi
        run: sushi igRepo

      - name: 🏃‍♂️ Run IG Publisher
        run : java -Xmx8192m -jar publisher.jar publisher -ig igRepo/.  

      - name: Get From site esante     
        run: |
          #Recuperation des fichier .json
          wget -q https://esante.gouv.fr/sites/default/files/media_entity/documents/NOS-Fichiers_Publics-Versions_json_fhir.zip
          cp  NOS-Fichiers_Publics-Versions_json_fhir.zip ./IG-website-release/www/ig/nos/NOS
          unzip -o NOS-Fichiers_Publics-Versions_json_fhir.zip -d ./IG-website-release/www/ig/nos/NOS          
          
          #Recucperation des fichiers .tabs
          wget -q https://esante.gouv.fr/sites/default/files/media_entity/documents/NOS-Fichiers_Publics.zip
          cp  NOS-Fichiers_Publics.zip ./IG-website-release/www/ig/nos/NOS/
          unzip -o NOS-Fichiers_Publics.zip -d ./IG-website-release/www/ig/nos/NOS

          #Recupération des fichiers SVS
          wget -q https://esante.gouv.fr/sites/default/files/media_entity/documents/NOS-Fichiers_Publics-Versions_xml_svs.zip
          cp  NOS-Fichiers_Publics-Versions_xml_svs.zip ./IG-website-release/www/ig/nos/NOS
          unzip  -o NOS-Fichiers_Publics-Versions_xml_svs.zip -d ./IG-website-release/www/ig/nos/NOS

          #Recupération des fichiers xml Fhir
          wget -q https://esante.gouv.fr/sites/default/files/media_entity/documents/nos-fichiers_publics-versions_xml_fhir.zip
          cp  nos-fichiers_publics-versions_xml_fhir.zip ./IG-website-release/www/ig/nos/NOS
          unzip -o nos-fichiers_publics-versions_xml_fhir.zip -d ./IG-website-release/www/ig/nos/NOS

          #Recuperation des fichiers PDF
          wget -q https://esante.gouv.fr/sites/default/files/media_entity/documents/NOS-Fichiers_Publics_JDV-Versions_pdf.zip
          cp  NOS-Fichiers_Publics_JDV-Versions_pdf.zip ./IG-website-release/www/ig/nos/NOS
          unzip -o NOS-Fichiers_Publics_JDV-Versions_pdf.zip -d ./IG-website-release/www/ig/nos/NOS
          wget -q https://esante.gouv.fr/sites/default/files/media_entity/documents/NOS-Fichiers_Publics_TRE_ASS-Versions_pdf.zip
          cp  NOS-Fichiers_Publics_TRE_ASS-Versions_pdf.zip ./IG-website-release/www/ig/nos/NOS
          unzip -o NOS-Fichiers_Publics_TRE_ASS-Versions_pdf.zip -d ./IG-website-release/www/ig/nos/NOS   


      - name: Install rename        
        run : sudo  apt install rename  

      - name:  Rename TRE
        run :  rename -v 's/TRE_/CodeSystem-TRE-/' ./IG-website-release/www/ig/nos/NOS/*

      - name:  Rename JDV
        run :  rename -v 's/JDV_/ValueSet-JDV-/' ./IG-website-release/www/ig/nos/NOS/*       


      - name:  1 ZIP JDV PDF
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-jdv-pdf.zip ./IG-website-release/www/ig/nos/NOS/*JDV-*.pdf        
        
      - name:  1 ZIP JDV SVS
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-jdv-svs.zip ./IG-website-release/www/ig/nos/NOS/*JDV-*.xml  -x "*FHIR*"   
        
      - name:  1 ZIP JDV FHIR JSON
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-jdv-fhir-json.zip ./IG-website-release/www/ig/nos/NOS/*JDV-*-FHIR.json     
        
      - name:  1 ZIP JDV FHIR XML
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-jdv-fhir-xml.zip ./IG-website-release/www/ig/nos/NOS/*JDV-*-FHIR.xml         
        
      - name:  1 ZIP JDV FHIR tabs
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-jdv-tabs.zip ./IG-website-release/www/ig/nos/NOS/*JDV-*.tabs 
        
      - name:  2 ZIP TRE PDF
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-tre-pdf.zip ./IG-website-release/www/ig/nos/NOS/*TRE-*.pdf        
        
      - name:  2 ZIP TRE SVS
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-tre-svs.zip ./IG-website-release/www/ig/nos/NOS/*TRE*.xml  -x "*FHIR*"   
        
      - name:  2 ZIP TRE FHIR JSON
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-tre-fhir-json.zip ./IG-website-release/www/ig/nos/NOS/*TRE*-FHIR.json     
        
      - name:  2 ZIP TRE FHIR XML
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-tre-fhir-xml.zip ./IG-website-release/www/ig/nos/NOS/*TRE*-FHIR.xml         
        
      - name:  2 ZIP TRE FHIR tabs
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-tre-tabs.zip ./IG-website-release/www/ig/nos/NOS/*TRE*.tabs 
        
    
      - name:  3 ZIP ASS PDF
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-ass-pdf.zip ./IG-website-release/www/ig/nos/NOS/ASS_*.pdf        
        
      - name:  3 ZIP ASS SVS
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-ass-svs.zip ./IG-website-release/www/ig/nos/NOS/ASS*.xml  -x "*FHIR*"   
        
      - name:  3 ZIP ASS FHIR JSON
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-ass-fhir-json.zip ./IG-website-release/www/ig/nos/NOS/ASS*-FHIR.json     
        
      - name:  3 ZIP ASS FHIR XML
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-ass-fhir-xml.zip ./IG-website-release/www/ig/nos/NOS/ASS*-FHIR.xml         
        
      - name:  3 ZIP ASS FHIR tabs
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-ass-tabs.zip ./IG-website-release/www/ig/nos/NOS/ASS*.tabs     
    
        
      - name:  ZIP Ensemble des NOS au format CSV 
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-Fichiers_Publics.zip ./IG-website-release/www/ig/nos/NOS/*.tabs  
 
      - name:  ZIP Ensemble des NOS au format XML/SVS 
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS-Fichiers_Publics-Versions_xml_svs.zip ./IG-website-release/www/ig/nos/NOS/*.xml  -x "*FHIR*"    

      - name:  ZIP Ensemble des NOS au format JSON/FHIR (ZIP)
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-Fichiers_Publics-Versions_json_fhir.zip ./IG-website-release/www/ig/nos/NOS/*-FHIR.json    

      #- name:  ZIP Ensemble des NOS au format XML/FHIR (ZIP)
      #  run :  zip -rj ./IG-website-release/www/ig/nos/NOS/Nos-fichiers_publics-versions_xml_fhir.zip ./IG-website-release/www/ig/nos/NOS/*-FHIR.xml   

      - name:  ZIP Jeux de valeurs du CI-SIS (ZIP
        run :  zip -rj ./IG-website-release/www/ig/nos/NOS/NOS-Jeux_de_Valeurs_CI-SIS.zip ./IG-website-release/www/ig/nos/NOS/*CISIS*            
          




      # Builds the HTML page for the IG.
      - name: 🏃‍♂️ Generate package registry
        run : java -Dfile.encoding=UTF-8 -jar publisher.jar -generate-package-registry ./IG-website-release
        
      - name: 🏃‍♂️ Run  Publisher to release
        run :   java -Dfile.encoding=UTF-8 -jar publisher.jar -go-publish -source igRepo -web  ./IG-website-release/www/ig -registry ./IG-website-release/ig-registry/fhir-ig-list.json -history ./IG-website-release/fhir-ig-history-template -templates ./IG-website-release/templates    -temp      /home/runner/work/publication/temp 
        
      - name: Commit change on IG-website-release
        run: |
          cd  IG-website-release
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A 
          git commit -m updated
          
      - name: Push changes on IG-website-release
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ANS_IG_API_TOKEN }}
          directory: IG-website-release
          repository : ansforge/IG-website-release
          force : true
